package com.veeps.app.feature.contentRail.model

import com.google.gson.annotations.SerializedName

data class Entities(
	@SerializedName("access") var access: ArrayList<String> = arrayListOf(),
	@SerializedName("event_access") var eventAccess: ArrayList<String> = arrayListOf(),
	@SerializedName("id") var id: String? = null,
	@SerializedName("ownership_status") var ownershipStatus: String? = null,
	@SerializedName("transfer_details") var transferDetails: Any? = null,
	@SerializedName("name") var name: String? = null,
	@SerializedName("status") var status: String? = null,
	@SerializedName("url") var url: String? = null,
	@SerializedName("event_name") var eventName: String? = null,
	@SerializedName("event_id") var eventId: String? = null,
	@SerializedName("venue_id") var venueId: String? = null,
	@SerializedName("event_stream_starts_at") var eventStreamStartsAt: String? = null,
	@SerializedName("event_rewatch_duration") var eventReWatchDuration: String? = null,
	@SerializedName("watch_status") var watchStatus: String? = null,
	@SerializedName("watch_until") var watchUntil: String? = null,
	@SerializedName("gating") var gating: String? = null,
	@SerializedName("subscriber_access_ends_at") var subscriberAccessEndsAt: String? = null,
	@SerializedName("on_sale_status") var onSaleStatus: String? = null,
	@SerializedName("lineup") var lineup: ArrayList<Lineup> = arrayListOf(),
	@SerializedName("event_currency") var eventCurrency: String? = null,
	@SerializedName("event_description") var eventDescription: String? = null,
	@SerializedName("event_poster_url") var eventPosterUrl: String? = null,
	@SerializedName("event_time_zone") var eventTimeZone: String? = null,
	@SerializedName("time_zone") var timeZone: String? = null,
	@SerializedName("on_sale_at") var onSaleAt: String? = null,
	@SerializedName("on_sale_end") var onSaleEnd: String? = null,
	@SerializedName("organization_name") var organizationName: String? = null,
	@SerializedName("organization_subdomain") var organizationSubdomain: String? = null,
	@SerializedName("user_playback_information") var userPlaybackInformation: UserPlaybackInformation = UserPlaybackInformation(),
	@SerializedName("links") var links: Links = Links(),
	@SerializedName("chat") var chat: Chat = Chat(),
	@SerializedName("playback") var playback: Playback = Playback(),
	@SerializedName("storyboards") var storyboards: Storyboards = Storyboards(),
	@SerializedName("event_portrait_url") var eventPortraitUrl: String? = null,
	@SerializedName("organization_facebook_pixel_id") var organizationFacebookPixelId: String? = null,
	@SerializedName("organization_google_analytics_id") var organizationGoogleAnalyticsId: String? = null,
	@SerializedName("presentation") var presentation: Presentation = Presentation(),
	@SerializedName("venue_landscape_url") var venueLandscapeUrl: String? = null,
	@SerializedName("landscape_url") var landscapeUrl: String? = null,
	@SerializedName("venue_logo_url") var venueLogoUrl: String? = null,
	@SerializedName("logo_url") var logoUrl: String? = null,
	@SerializedName("venue_name") var venueName: String? = null,
	@SerializedName("venue_portrait_url") var venuePortraitUrl: String? = null,
	@SerializedName("portrait_url") var portraitUrl: String? = null,
	@SerializedName("last_signal") var lastSignal: String? = null,
	@SerializedName("event_doors_at") var eventDoorsAt: String? = null,
	@SerializedName("stream_url") var streamUrl: String? = null,
	@SerializedName("video_previews") var videoPreviews: Any? = null,
	@SerializedName("has_collections") var hasCollections: Boolean = false,
)
